plugins: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

# ドキュメントコメント不要
Style/Documentation:
  Enabled: false

# 国際化対応は対象外
Rails/I18nLocaleTexts:
  Enabled: false

# spec ファイルはテストの可読性のためブロック長を緩和
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# spec ファイルはメソッド長を緩和
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/ClassLength:
  Max: 110
